/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;

/**
 *
 * @author Joaquim Pereira
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        SenhaText = new javax.swing.JPasswordField();
        senha = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        FecharBt = new javax.swing.JButton();
        AcessarBT = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 600));

        Principal.setBackground(new java.awt.Color(57, 53, 53));

        Login.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        Login.setToolTipText(null);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Login.setRequestFocusEnabled(false);
        Login.setVerifyInputWhenFocusTarget(false);

        EmailText.setBackground(new java.awt.Color(85, 79, 79));
        EmailText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailText.setForeground(new java.awt.Color(255, 255, 255));
        EmailText.setToolTipText("Digite seu E-mail");
        EmailText.setBorder(null);
        EmailText.setMargin(new java.awt.Insets(3, 3, 3, 3));

        SenhaText.setBackground(new java.awt.Color(85, 79, 79));
        SenhaText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SenhaText.setForeground(new java.awt.Color(255, 255, 255));
        SenhaText.setToolTipText("Digite sua senha");
        SenhaText.setBorder(null);
        SenhaText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        SenhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaTextActionPerformed(evt);
            }
        });

        senha.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setText("Senha:");

        Email.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email:");

        FecharBt.setBackground(new java.awt.Color(57, 53, 53));
        FecharBt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        FecharBt.setForeground(new java.awt.Color(255, 255, 255));
        FecharBt.setText("x");
        FecharBt.setToolTipText("Fechar");
        FecharBt.setBorder(null);
        FecharBt.setContentAreaFilled(false);
        FecharBt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FecharBt.setFocusable(false);
        FecharBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FecharBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FecharBtMouseExited(evt);
            }
        });
        FecharBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharBtActionPerformed(evt);
            }
        });

        AcessarBT.setBackground(new java.awt.Color(81, 149, 124));
        AcessarBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AcessarBT.setForeground(new java.awt.Color(255, 255, 255));
        AcessarBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcessarBT.setText("Acessar");
        AcessarBT.setMaximumSize(new java.awt.Dimension(79, 33));
        AcessarBT.setMinimumSize(new java.awt.Dimension(79, 33));
        AcessarBT.setOpaque(true);
        AcessarBT.setPreferredSize(new java.awt.Dimension(79, 33));
        AcessarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcessarBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AcessarBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AcessarBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcessarBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AcessarBTMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FecharBt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AcessarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SenhaText)
                    .addComponent(EmailText)
                    .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addComponent(FecharBt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Login)
                .addGap(56, 56, 56)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(AcessarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(Principal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FecharBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FecharBtActionPerformed

    private void SenhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaTextActionPerformed

    private void FecharBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharBtMouseClicked
        // fechar a tela caso for clicado
        System.exit(0);
    }//GEN-LAST:event_FecharBtMouseClicked

    private void FecharBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharBtMouseEntered
        // muda de cor quando mouse entra 
        FecharBt.setForeground(Color.red);
    }//GEN-LAST:event_FecharBtMouseEntered

    private void FecharBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharBtMouseExited
        //muda cor quando mouse sai
        FecharBt.setForeground(Color.white);
    }//GEN-LAST:event_FecharBtMouseExited

    private void AcessarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcessarBTMouseClicked
        //chama o menu principal
         FrmTP frm = new FrmTP(); 
        frm.setVisible(true); 
        dispose(); 

    }//GEN-LAST:event_AcessarBTMouseClicked

    private void AcessarBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcessarBTMouseEntered
        //troca a cor do fundo quando o mouse entra na area do botão
        AcessarBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_AcessarBTMouseEntered

    private void AcessarBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcessarBTMouseExited
        //troca a cor do botao quanddo o mouse sai da area dele
        AcessarBT.setBackground(new Color(89, 149, 124));
    }//GEN-LAST:event_AcessarBTMouseExited

    private void AcessarBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcessarBTMousePressed
        // troca a cor do botao quando ele for precionado
        AcessarBT.setBackground(new Color(74, 129, 107));
    }//GEN-LAST:event_AcessarBTMousePressed

    private void AcessarBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcessarBTMouseReleased
        // troca a cor do botao quando ele for solto:
        AcessarBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_AcessarBTMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcessarBT;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailText;
    private javax.swing.JButton FecharBt;
    private javax.swing.JLabel Login;
    private javax.swing.JPanel Principal;
    private javax.swing.JPasswordField SenhaText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel senha;
    // End of variables declaration//GEN-END:variables
}
