/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import gymmac.Conexao;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import tabelas.CadastroAcad;

/**
 *
 * @author Joaquim Pereira 
 */
public class FrmTP extends javax.swing.JFrame {
    

    /**
     * Creates new form FrmTP
     */
    public FrmTP() {
        
        initComponents();
        JTableHeader JTM = SelecionarAcademia.getTableHeader();
        JTM.setBackground(new Color(69,64,64));
        JTM.setForeground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Janelas = new javax.swing.JTabbedPane();
        TelaPrincipalPane = new javax.swing.JPanel();
        CadastroAcademiaPane = new javax.swing.JPanel();
        cadastroacademia = new javax.swing.JLabel();
        RazaoSocial = new javax.swing.JLabel();
        NomeFantasia = new javax.swing.JLabel();
        NomeResponsavel = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Cep = new javax.swing.JLabel();
        RazaoSocialText = new javax.swing.JTextField();
        NomeFantasiaText = new javax.swing.JTextField();
        NomeResponsavelText = new javax.swing.JTextField();
        CnpjText = new javax.swing.JTextField();
        TelefoneText = new javax.swing.JTextField();
        CepText = new javax.swing.JTextField();
        CancelarAcademiaBT = new javax.swing.JLabel();
        SalvarAcademiaBT = new javax.swing.JLabel();
        CadastroEquipamentoPane = new javax.swing.JPanel();
        CadastroEquipamentos = new javax.swing.JLabel();
        NomeEquipamento = new javax.swing.JLabel();
        NumSerie = new javax.swing.JLabel();
        CnpjEquipamento = new javax.swing.JLabel();
        NumSerieText = new javax.swing.JTextField();
        CnpjEquipamentoText = new javax.swing.JTextField();
        NomeEquipamentoText1 = new javax.swing.JTextField();
        CancelarEquipamentoBT = new javax.swing.JLabel();
        SalvarAcademiaBT1 = new javax.swing.JLabel();
        SelecionarPane = new javax.swing.JPanel();
        CadastroEquipamentos1 = new javax.swing.JLabel();
        NumSerie1 = new javax.swing.JLabel();
        CnpjPesquisa = new javax.swing.JFormattedTextField();
        RazaoSocialSelecionar = new javax.swing.JTextField();
        CNPJ1 = new javax.swing.JLabel();
        SalvarBT1 = new javax.swing.JButton();
        TabelaScrollPane = new javax.swing.JScrollPane();
        SelecionarAcademia = new javax.swing.JTable();
        CadAcademiaPane4 = new javax.swing.JPanel();
        CadAcademiaPane5 = new javax.swing.JPanel();
        FecharBt = new javax.swing.JButton();
        SelecionarBT = new javax.swing.JLabel();
        CadAcademiaBT = new javax.swing.JLabel();
        CadEquipamentoBT = new javax.swing.JLabel();
        RelatorioBT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);

        Principal.setBackground(new java.awt.Color(69, 64, 64));

        Janelas.setBackground(new java.awt.Color(57, 53, 53));
        Janelas.setForeground(new java.awt.Color(255, 255, 255));
        Janelas.setMaximumSize(new java.awt.Dimension(1445, 1080));
        Janelas.setMinimumSize(new java.awt.Dimension(1445, 1080));
        Janelas.setPreferredSize(new java.awt.Dimension(1445, 1080));

        TelaPrincipalPane.setBackground(new java.awt.Color(57, 53, 53));

        javax.swing.GroupLayout TelaPrincipalPaneLayout = new javax.swing.GroupLayout(TelaPrincipalPane);
        TelaPrincipalPane.setLayout(TelaPrincipalPaneLayout);
        TelaPrincipalPaneLayout.setHorizontalGroup(
            TelaPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        TelaPrincipalPaneLayout.setVerticalGroup(
            TelaPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );

        Janelas.addTab("tabela principal", TelaPrincipalPane);

        CadastroAcademiaPane.setBackground(new java.awt.Color(57, 53, 53));

        cadastroacademia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cadastroacademia.setForeground(new java.awt.Color(255, 255, 255));
        cadastroacademia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastroacademia.setText("Cadastro de Academias");
        cadastroacademia.setFocusable(false);
        cadastroacademia.setMaximumSize(new java.awt.Dimension(505, 100));
        cadastroacademia.setMinimumSize(new java.awt.Dimension(505, 100));
        cadastroacademia.setPreferredSize(new java.awt.Dimension(505, 100));

        RazaoSocial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RazaoSocial.setForeground(new java.awt.Color(255, 255, 255));
        RazaoSocial.setText("Razão Social:");
        RazaoSocial.setFocusable(false);

        NomeFantasia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NomeFantasia.setForeground(new java.awt.Color(255, 255, 255));
        NomeFantasia.setText("Nome Fantasia:");
        NomeFantasia.setFocusable(false);

        NomeResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NomeResponsavel.setForeground(new java.awt.Color(255, 255, 255));
        NomeResponsavel.setText("Nome Responsavel:");
        NomeResponsavel.setFocusable(false);

        CNPJ.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CNPJ.setForeground(new java.awt.Color(255, 255, 255));
        CNPJ.setText("CNPJ:");
        CNPJ.setFocusable(false);

        Telefone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Telefone.setForeground(new java.awt.Color(255, 255, 255));
        Telefone.setText("Telefone:");
        Telefone.setFocusable(false);

        Cep.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Cep.setForeground(new java.awt.Color(255, 255, 255));
        Cep.setText("CEP:");
        Cep.setFocusable(false);

        RazaoSocialText.setBackground(new java.awt.Color(85, 79, 79));
        RazaoSocialText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RazaoSocialText.setForeground(new java.awt.Color(255, 255, 255));
        RazaoSocialText.setToolTipText("");
        RazaoSocialText.setBorder(null);
        RazaoSocialText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        RazaoSocialText.setMaximumSize(new java.awt.Dimension(1321, 33));
        RazaoSocialText.setMinimumSize(new java.awt.Dimension(1321, 33));
        RazaoSocialText.setPreferredSize(new java.awt.Dimension(1321, 33));
        RazaoSocialText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazaoSocialTextActionPerformed(evt);
            }
        });

        NomeFantasiaText.setBackground(new java.awt.Color(85, 79, 79));
        NomeFantasiaText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeFantasiaText.setForeground(new java.awt.Color(255, 255, 255));
        NomeFantasiaText.setToolTipText("");
        NomeFantasiaText.setBorder(null);
        NomeFantasiaText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        NomeFantasiaText.setMaximumSize(new java.awt.Dimension(820, 33));
        NomeFantasiaText.setMinimumSize(new java.awt.Dimension(820, 33));
        NomeFantasiaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFantasiaTextActionPerformed(evt);
            }
        });

        NomeResponsavelText.setBackground(new java.awt.Color(85, 79, 79));
        NomeResponsavelText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeResponsavelText.setForeground(new java.awt.Color(255, 255, 255));
        NomeResponsavelText.setToolTipText("");
        NomeResponsavelText.setBorder(null);
        NomeResponsavelText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        NomeResponsavelText.setMaximumSize(new java.awt.Dimension(820, 33));
        NomeResponsavelText.setMinimumSize(new java.awt.Dimension(820, 33));
        NomeResponsavelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeResponsavelTextActionPerformed(evt);
            }
        });

        CnpjText.setBackground(new java.awt.Color(85, 79, 79));
        CnpjText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CnpjText.setForeground(new java.awt.Color(255, 255, 255));
        CnpjText.setToolTipText("");
        CnpjText.setBorder(null);
        CnpjText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        CnpjText.setMaximumSize(new java.awt.Dimension(820, 33));
        CnpjText.setMinimumSize(new java.awt.Dimension(820, 33));
        CnpjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnpjTextActionPerformed(evt);
            }
        });

        TelefoneText.setBackground(new java.awt.Color(85, 79, 79));
        TelefoneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TelefoneText.setForeground(new java.awt.Color(255, 255, 255));
        TelefoneText.setToolTipText("");
        TelefoneText.setBorder(null);
        TelefoneText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        TelefoneText.setMaximumSize(new java.awt.Dimension(820, 33));
        TelefoneText.setMinimumSize(new java.awt.Dimension(820, 33));
        TelefoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneTextActionPerformed(evt);
            }
        });

        CepText.setBackground(new java.awt.Color(85, 79, 79));
        CepText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CepText.setForeground(new java.awt.Color(255, 255, 255));
        CepText.setToolTipText("");
        CepText.setBorder(null);
        CepText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        CepText.setMaximumSize(new java.awt.Dimension(820, 33));
        CepText.setMinimumSize(new java.awt.Dimension(820, 33));
        CepText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CepTextActionPerformed(evt);
            }
        });

        CancelarAcademiaBT.setBackground(new java.awt.Color(229, 81, 49));
        CancelarAcademiaBT.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CancelarAcademiaBT.setForeground(new java.awt.Color(255, 255, 255));
        CancelarAcademiaBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelarAcademiaBT.setText("Cancelar");
        CancelarAcademiaBT.setFocusable(false);
        CancelarAcademiaBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CancelarAcademiaBT.setMaximumSize(new java.awt.Dimension(350, 100));
        CancelarAcademiaBT.setMinimumSize(new java.awt.Dimension(350, 100));
        CancelarAcademiaBT.setOpaque(true);
        CancelarAcademiaBT.setPreferredSize(new java.awt.Dimension(350, 100));
        CancelarAcademiaBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarAcademiaBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarAcademiaBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarAcademiaBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelarAcademiaBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelarAcademiaBTMouseReleased(evt);
            }
        });

        SalvarAcademiaBT.setBackground(new java.awt.Color(89, 149, 124));
        SalvarAcademiaBT.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        SalvarAcademiaBT.setForeground(new java.awt.Color(255, 255, 255));
        SalvarAcademiaBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalvarAcademiaBT.setText("Salvar");
        SalvarAcademiaBT.setFocusable(false);
        SalvarAcademiaBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SalvarAcademiaBT.setMaximumSize(new java.awt.Dimension(350, 100));
        SalvarAcademiaBT.setMinimumSize(new java.awt.Dimension(350, 100));
        SalvarAcademiaBT.setOpaque(true);
        SalvarAcademiaBT.setPreferredSize(new java.awt.Dimension(350, 100));
        SalvarAcademiaBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBTMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CadastroAcademiaPaneLayout = new javax.swing.GroupLayout(CadastroAcademiaPane);
        CadastroAcademiaPane.setLayout(CadastroAcademiaPaneLayout);
        CadastroAcademiaPaneLayout.setHorizontalGroup(
            CadastroAcademiaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroAcademiaPaneLayout.createSequentialGroup()
                .addGroup(CadastroAcademiaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroAcademiaPaneLayout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(cadastroacademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroAcademiaPaneLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(CadastroAcademiaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastroAcademiaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(CadastroAcademiaPaneLayout.createSequentialGroup()
                                    .addComponent(CancelarAcademiaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SalvarAcademiaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CepText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TelefoneText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CnpjText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NomeResponsavelText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NomeFantasiaText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RazaoSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NomeFantasia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RazaoSocialText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CNPJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        CadastroAcademiaPaneLayout.setVerticalGroup(
            CadastroAcademiaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroAcademiaPaneLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cadastroacademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(RazaoSocialText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(NomeFantasiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(NomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(NomeResponsavelText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CnpjText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TelefoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CepText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addGroup(CadastroAcademiaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarAcademiaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarAcademiaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        Janelas.addTab("cadastro academia", CadastroAcademiaPane);

        CadastroEquipamentoPane.setBackground(new java.awt.Color(57, 53, 53));

        CadastroEquipamentos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CadastroEquipamentos.setForeground(new java.awt.Color(255, 255, 255));
        CadastroEquipamentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastroEquipamentos.setText("Cadastro de Equipamentos");
        CadastroEquipamentos.setFocusable(false);
        CadastroEquipamentos.setMaximumSize(new java.awt.Dimension(505, 100));
        CadastroEquipamentos.setMinimumSize(new java.awt.Dimension(505, 100));
        CadastroEquipamentos.setPreferredSize(new java.awt.Dimension(505, 100));

        NomeEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NomeEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        NomeEquipamento.setText("Nome do Equiapemento:");
        NomeEquipamento.setFocusable(false);

        NumSerie.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NumSerie.setForeground(new java.awt.Color(255, 255, 255));
        NumSerie.setText("Número de Série:");
        NumSerie.setFocusable(false);

        CnpjEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CnpjEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        CnpjEquipamento.setText("CNPJ da Academia:");
        CnpjEquipamento.setFocusable(false);

        NumSerieText.setBackground(new java.awt.Color(85, 79, 79));
        NumSerieText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumSerieText.setForeground(new java.awt.Color(255, 255, 255));
        NumSerieText.setToolTipText("");
        NumSerieText.setBorder(null);
        NumSerieText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        NumSerieText.setMaximumSize(new java.awt.Dimension(820, 33));
        NumSerieText.setMinimumSize(new java.awt.Dimension(820, 33));
        NumSerieText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumSerieTextActionPerformed(evt);
            }
        });

        CnpjEquipamentoText.setBackground(new java.awt.Color(85, 79, 79));
        CnpjEquipamentoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CnpjEquipamentoText.setForeground(new java.awt.Color(255, 255, 255));
        CnpjEquipamentoText.setToolTipText("");
        CnpjEquipamentoText.setBorder(null);
        CnpjEquipamentoText.setMargin(new java.awt.Insets(2, 4, 2, 2));
        CnpjEquipamentoText.setMaximumSize(new java.awt.Dimension(820, 33));
        CnpjEquipamentoText.setMinimumSize(new java.awt.Dimension(820, 33));
        CnpjEquipamentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnpjEquipamentoTextActionPerformed(evt);
            }
        });

        NomeEquipamentoText1.setBackground(new java.awt.Color(85, 79, 79));
        NomeEquipamentoText1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeEquipamentoText1.setForeground(new java.awt.Color(255, 255, 255));
        NomeEquipamentoText1.setToolTipText("");
        NomeEquipamentoText1.setBorder(null);
        NomeEquipamentoText1.setMargin(new java.awt.Insets(2, 4, 2, 2));
        NomeEquipamentoText1.setMaximumSize(new java.awt.Dimension(1321, 33));
        NomeEquipamentoText1.setMinimumSize(new java.awt.Dimension(1321, 33));
        NomeEquipamentoText1.setPreferredSize(new java.awt.Dimension(1321, 33));
        NomeEquipamentoText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeEquipamentoText1ActionPerformed(evt);
            }
        });

        CancelarEquipamentoBT.setBackground(new java.awt.Color(229, 81, 49));
        CancelarEquipamentoBT.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CancelarEquipamentoBT.setForeground(new java.awt.Color(255, 255, 255));
        CancelarEquipamentoBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelarEquipamentoBT.setText("Cancelar");
        CancelarEquipamentoBT.setFocusable(false);
        CancelarEquipamentoBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CancelarEquipamentoBT.setMaximumSize(new java.awt.Dimension(350, 100));
        CancelarEquipamentoBT.setMinimumSize(new java.awt.Dimension(350, 100));
        CancelarEquipamentoBT.setOpaque(true);
        CancelarEquipamentoBT.setPreferredSize(new java.awt.Dimension(350, 100));
        CancelarEquipamentoBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarEquipamentoBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarEquipamentoBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarEquipamentoBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelarEquipamentoBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelarEquipamentoBTMouseReleased(evt);
            }
        });

        SalvarAcademiaBT1.setBackground(new java.awt.Color(89, 149, 124));
        SalvarAcademiaBT1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        SalvarAcademiaBT1.setForeground(new java.awt.Color(255, 255, 255));
        SalvarAcademiaBT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalvarAcademiaBT1.setText("Salvar");
        SalvarAcademiaBT1.setFocusable(false);
        SalvarAcademiaBT1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SalvarAcademiaBT1.setMaximumSize(new java.awt.Dimension(350, 100));
        SalvarAcademiaBT1.setMinimumSize(new java.awt.Dimension(350, 100));
        SalvarAcademiaBT1.setOpaque(true);
        SalvarAcademiaBT1.setPreferredSize(new java.awt.Dimension(350, 100));
        SalvarAcademiaBT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBT1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBT1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBT1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBT1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SalvarAcademiaBT1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CadastroEquipamentoPaneLayout = new javax.swing.GroupLayout(CadastroEquipamentoPane);
        CadastroEquipamentoPane.setLayout(CadastroEquipamentoPaneLayout);
        CadastroEquipamentoPaneLayout.setHorizontalGroup(
            CadastroEquipamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroEquipamentoPaneLayout.createSequentialGroup()
                .addGroup(CadastroEquipamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroEquipamentoPaneLayout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(CadastroEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroEquipamentoPaneLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(CadastroEquipamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CnpjEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumSerieText, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeEquipamentoText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastroEquipamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(CadastroEquipamentoPaneLayout.createSequentialGroup()
                                    .addComponent(CancelarEquipamentoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SalvarAcademiaBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CnpjEquipamentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        CadastroEquipamentoPaneLayout.setVerticalGroup(
            CadastroEquipamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroEquipamentoPaneLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(CadastroEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(NomeEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(NomeEquipamentoText1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(NumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(NumSerieText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(CnpjEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CnpjEquipamentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440)
                .addGroup(CadastroEquipamentoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarEquipamentoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalvarAcademiaBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        Janelas.addTab("cadastro de equipamento", CadastroEquipamentoPane);

        SelecionarPane.setBackground(new java.awt.Color(57, 53, 53));

        CadastroEquipamentos1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CadastroEquipamentos1.setForeground(new java.awt.Color(255, 255, 255));
        CadastroEquipamentos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastroEquipamentos1.setText("Selecionar Academia");
        CadastroEquipamentos1.setFocusable(false);
        CadastroEquipamentos1.setMaximumSize(new java.awt.Dimension(457, 100));
        CadastroEquipamentos1.setMinimumSize(new java.awt.Dimension(457, 100));
        CadastroEquipamentos1.setPreferredSize(new java.awt.Dimension(457, 100));

        NumSerie1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NumSerie1.setForeground(new java.awt.Color(255, 255, 255));
        NumSerie1.setText("Razão Social:");
        NumSerie1.setFocusable(false);
        NumSerie1.setMaximumSize(new java.awt.Dimension(250, 33));
        NumSerie1.setMinimumSize(new java.awt.Dimension(250, 33));
        NumSerie1.setPreferredSize(new java.awt.Dimension(250, 33));

        CnpjPesquisa.setBackground(new java.awt.Color(85, 79, 79));
        CnpjPesquisa.setBorder(null);
        CnpjPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        CnpjPesquisa.setFocusable(false);
        CnpjPesquisa.setMaximumSize(new java.awt.Dimension(350, 33));
        CnpjPesquisa.setMinimumSize(new java.awt.Dimension(350, 33));
        CnpjPesquisa.setPreferredSize(new java.awt.Dimension(350, 33));

        RazaoSocialSelecionar.setBackground(new java.awt.Color(85, 79, 79));
        RazaoSocialSelecionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RazaoSocialSelecionar.setForeground(new java.awt.Color(255, 255, 255));
        RazaoSocialSelecionar.setToolTipText("");
        RazaoSocialSelecionar.setBorder(null);
        RazaoSocialSelecionar.setMargin(new java.awt.Insets(2, 4, 2, 2));
        RazaoSocialSelecionar.setMaximumSize(new java.awt.Dimension(350, 33));
        RazaoSocialSelecionar.setMinimumSize(new java.awt.Dimension(350, 33));
        RazaoSocialSelecionar.setPreferredSize(new java.awt.Dimension(350, 33));
        RazaoSocialSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazaoSocialSelecionarActionPerformed(evt);
            }
        });

        CNPJ1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CNPJ1.setForeground(new java.awt.Color(255, 255, 255));
        CNPJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CNPJ1.setText("CNPJ:");
        CNPJ1.setFocusable(false);

        SalvarBT1.setBackground(new java.awt.Color(81, 149, 124));
        SalvarBT1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SalvarBT1.setForeground(new java.awt.Color(255, 255, 255));
        SalvarBT1.setText("Pesquisar");
        SalvarBT1.setBorder(null);
        SalvarBT1.setFocusable(false);
        SalvarBT1.setMaximumSize(new java.awt.Dimension(350, 100));
        SalvarBT1.setMinimumSize(new java.awt.Dimension(350, 100));
        SalvarBT1.setPreferredSize(new java.awt.Dimension(350, 100));
        SalvarBT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarBT1MouseClicked(evt);
            }
        });
        SalvarBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBT1ActionPerformed(evt);
            }
        });

        SelecionarAcademia.setBackground(new java.awt.Color(59, 64, 62));
        SelecionarAcademia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SelecionarAcademia.setForeground(new java.awt.Color(255, 255, 255));
        SelecionarAcademia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "razão social", "nome responsavel", "Telefone", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SelecionarAcademia.setFocusable(false);
        SelecionarAcademia.setMaximumSize(new java.awt.Dimension(1363, 757));
        SelecionarAcademia.setMinimumSize(new java.awt.Dimension(1363, 757));
        SelecionarAcademia.setPreferredSize(new java.awt.Dimension(1363, 757));
        SelecionarAcademia.setSelectionBackground(new java.awt.Color(204, 204, 204));
        SelecionarAcademia.getTableHeader().setReorderingAllowed(false);
        SelecionarAcademia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SelecionarAcademiaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TabelaScrollPane.setViewportView(SelecionarAcademia);

        javax.swing.GroupLayout SelecionarPaneLayout = new javax.swing.GroupLayout(SelecionarPane);
        SelecionarPane.setLayout(SelecionarPaneLayout);
        SelecionarPaneLayout.setHorizontalGroup(
            SelecionarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelecionarPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SelecionarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelecionarPaneLayout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(CadastroEquipamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SelecionarPaneLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(SelecionarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TabelaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SelecionarPaneLayout.createSequentialGroup()
                                .addComponent(NumSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(RazaoSocialSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(CNPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(CnpjPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalvarBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        SelecionarPaneLayout.setVerticalGroup(
            SelecionarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelecionarPaneLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(CadastroEquipamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(SelecionarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CNPJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RazaoSocialSelecionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NumSerie1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CnpjPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalvarBT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(TabelaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        Janelas.addTab("selecionar", SelecionarPane);

        CadAcademiaPane4.setBackground(new java.awt.Color(57, 53, 53));

        javax.swing.GroupLayout CadAcademiaPane4Layout = new javax.swing.GroupLayout(CadAcademiaPane4);
        CadAcademiaPane4.setLayout(CadAcademiaPane4Layout);
        CadAcademiaPane4Layout.setHorizontalGroup(
            CadAcademiaPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1445, Short.MAX_VALUE)
        );
        CadAcademiaPane4Layout.setVerticalGroup(
            CadAcademiaPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );

        Janelas.addTab("1", CadAcademiaPane4);

        CadAcademiaPane5.setBackground(new java.awt.Color(57, 53, 53));

        javax.swing.GroupLayout CadAcademiaPane5Layout = new javax.swing.GroupLayout(CadAcademiaPane5);
        CadAcademiaPane5.setLayout(CadAcademiaPane5Layout);
        CadAcademiaPane5Layout.setHorizontalGroup(
            CadAcademiaPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1445, Short.MAX_VALUE)
        );
        CadAcademiaPane5Layout.setVerticalGroup(
            CadAcademiaPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );

        Janelas.addTab("2", CadAcademiaPane5);

        FecharBt.setBackground(new java.awt.Color(57, 53, 53));
        FecharBt.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        FecharBt.setForeground(new java.awt.Color(255, 255, 255));
        FecharBt.setText("x");
        FecharBt.setToolTipText("Fechar");
        FecharBt.setBorder(null);
        FecharBt.setContentAreaFilled(false);
        FecharBt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FecharBt.setFocusable(false);
        FecharBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FecharBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FecharBtMouseExited(evt);
            }
        });
        FecharBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharBtActionPerformed(evt);
            }
        });

        SelecionarBT.setBackground(new java.awt.Color(89, 149, 124));
        SelecionarBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SelecionarBT.setForeground(new java.awt.Color(255, 255, 255));
        SelecionarBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelecionarBT.setText("Selecionar e Alteração");
        SelecionarBT.setFocusable(false);
        SelecionarBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SelecionarBT.setMaximumSize(new java.awt.Dimension(475, 80));
        SelecionarBT.setMinimumSize(new java.awt.Dimension(475, 80));
        SelecionarBT.setOpaque(true);
        SelecionarBT.setPreferredSize(new java.awt.Dimension(475, 80));
        SelecionarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelecionarBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SelecionarBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SelecionarBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SelecionarBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SelecionarBTMouseReleased(evt);
            }
        });

        CadAcademiaBT.setBackground(new java.awt.Color(89, 149, 124));
        CadAcademiaBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CadAcademiaBT.setForeground(new java.awt.Color(255, 255, 255));
        CadAcademiaBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadAcademiaBT.setText("Cadastrar Academias");
        CadAcademiaBT.setFocusable(false);
        CadAcademiaBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadAcademiaBT.setMaximumSize(new java.awt.Dimension(475, 80));
        CadAcademiaBT.setMinimumSize(new java.awt.Dimension(475, 80));
        CadAcademiaBT.setOpaque(true);
        CadAcademiaBT.setPreferredSize(new java.awt.Dimension(475, 80));
        CadAcademiaBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadAcademiaBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadAcademiaBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadAcademiaBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CadAcademiaBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CadAcademiaBTMouseReleased(evt);
            }
        });

        CadEquipamentoBT.setBackground(new java.awt.Color(89, 149, 124));
        CadEquipamentoBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CadEquipamentoBT.setForeground(new java.awt.Color(255, 255, 255));
        CadEquipamentoBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadEquipamentoBT.setText("Cadastrar Equipamentos");
        CadEquipamentoBT.setFocusable(false);
        CadEquipamentoBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadEquipamentoBT.setMaximumSize(new java.awt.Dimension(475, 80));
        CadEquipamentoBT.setMinimumSize(new java.awt.Dimension(475, 80));
        CadEquipamentoBT.setOpaque(true);
        CadEquipamentoBT.setPreferredSize(new java.awt.Dimension(475, 80));
        CadEquipamentoBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadEquipamentoBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadEquipamentoBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadEquipamentoBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CadEquipamentoBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CadEquipamentoBTMouseReleased(evt);
            }
        });

        RelatorioBT.setBackground(new java.awt.Color(89, 149, 124));
        RelatorioBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RelatorioBT.setForeground(new java.awt.Color(255, 255, 255));
        RelatorioBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RelatorioBT.setText("Relatorio de Despesas/Ganhos");
        RelatorioBT.setFocusable(false);
        RelatorioBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RelatorioBT.setMaximumSize(new java.awt.Dimension(475, 80));
        RelatorioBT.setMinimumSize(new java.awt.Dimension(475, 80));
        RelatorioBT.setOpaque(true);
        RelatorioBT.setPreferredSize(new java.awt.Dimension(475, 80));
        RelatorioBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RelatorioBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelatorioBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelatorioBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RelatorioBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RelatorioBTMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelecionarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelatorioBT, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FecharBt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CadEquipamentoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadAcademiaBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(Janelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(CadAcademiaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(CadEquipamentoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(SelecionarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(RelatorioBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(FecharBt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Janelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Principal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void FecharBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharBtMouseClicked
        // fechar a tela caso for clicado
        System.exit(0);
    }//GEN-LAST:event_FecharBtMouseClicked

    private void FecharBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharBtMouseEntered
        // muda de cor quando mouse entra
        FecharBt.setForeground(Color.red);
    }//GEN-LAST:event_FecharBtMouseEntered

    private void FecharBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharBtMouseExited
        //muda cor quando mouse sai
        FecharBt.setForeground(Color.white);
    }//GEN-LAST:event_FecharBtMouseExited

    private void FecharBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FecharBtActionPerformed

    private void CepTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CepTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CepTextActionPerformed

    private void TelefoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneTextActionPerformed

    private void CnpjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnpjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnpjTextActionPerformed

    private void NomeResponsavelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeResponsavelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeResponsavelTextActionPerformed

    private void NomeFantasiaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFantasiaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFantasiaTextActionPerformed

    private void RazaoSocialTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazaoSocialTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RazaoSocialTextActionPerformed

    private void RazaoSocialSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazaoSocialSelecionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RazaoSocialSelecionarActionPerformed

    private void NumSerieTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumSerieTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumSerieTextActionPerformed

    private void CnpjEquipamentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnpjEquipamentoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnpjEquipamentoTextActionPerformed

    private void NomeEquipamentoText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeEquipamentoText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeEquipamentoText1ActionPerformed

    private void SalvarBT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarBT1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarBT1MouseClicked

    private void SalvarBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarBT1ActionPerformed

    private void SelecionarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelecionarBTMouseClicked
        // troca para a tela cadastro de academias quando clicado
        Janelas.setSelectedIndex(3);
    }//GEN-LAST:event_SelecionarBTMouseClicked

    private void SelecionarBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelecionarBTMouseEntered
        //troca a cor do botao quanddo o mouse entra na area dele
        SelecionarBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_SelecionarBTMouseEntered

    private void SelecionarBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelecionarBTMouseExited
        //troca a cor do botao quanddo o mouse sai da area dele
        SelecionarBT.setBackground(new Color(89, 149, 124));
    }//GEN-LAST:event_SelecionarBTMouseExited

    private void SelecionarBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelecionarBTMousePressed
        // troca a cor do botao quando ele for precionado
        SelecionarBT.setBackground(new Color(74, 129, 107));
    }//GEN-LAST:event_SelecionarBTMousePressed

    private void SelecionarBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelecionarBTMouseReleased
        // troca a cor do botao quando ele for solto:
        SelecionarBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_SelecionarBTMouseReleased

    private void CadAcademiaBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadAcademiaBTMouseClicked
        // TODO add your handling code here:
        Janelas.setSelectedIndex(1);
    }//GEN-LAST:event_CadAcademiaBTMouseClicked

    private void CadAcademiaBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadAcademiaBTMouseEntered
        //troca a cor do botao quanddo o mouse entra na area dele
        CadAcademiaBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_CadAcademiaBTMouseEntered

    private void CadAcademiaBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadAcademiaBTMouseExited
        //troca a cor do botao quanddo o mouse sai da area dele
        CadAcademiaBT.setBackground(new Color(89, 149, 124));
    }//GEN-LAST:event_CadAcademiaBTMouseExited

    private void CadAcademiaBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadAcademiaBTMousePressed
        // troca a cor do botao quando ele for precionado
        CadAcademiaBT.setBackground(new Color(74, 129, 107));
    }//GEN-LAST:event_CadAcademiaBTMousePressed

    private void CadAcademiaBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadAcademiaBTMouseReleased
        // troca a cor do botao quando ele for solto:
        CadAcademiaBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_CadAcademiaBTMouseReleased

    private void CadEquipamentoBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadEquipamentoBTMouseClicked
        Janelas.setSelectedIndex(2);
    }//GEN-LAST:event_CadEquipamentoBTMouseClicked

    private void CadEquipamentoBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadEquipamentoBTMouseEntered
       //troca a cor do botao quanddo o mouse entra na area dele
        CadEquipamentoBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_CadEquipamentoBTMouseEntered

    private void CadEquipamentoBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadEquipamentoBTMouseExited
        //troca a cor do botao quanddo o mouse sai da area dele
        CadEquipamentoBT.setBackground(new Color(89, 149, 124));
    }//GEN-LAST:event_CadEquipamentoBTMouseExited

    private void CadEquipamentoBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadEquipamentoBTMousePressed
        // troca a cor do botao quando ele for precionado
        CadEquipamentoBT.setBackground(new Color(74, 129, 107));
    }//GEN-LAST:event_CadEquipamentoBTMousePressed

    private void CadEquipamentoBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadEquipamentoBTMouseReleased
        // troca a cor do botao quando ele for solto:
        CadEquipamentoBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_CadEquipamentoBTMouseReleased

    private void RelatorioBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatorioBTMouseClicked
        Janelas.setSelectedIndex(4);
    }//GEN-LAST:event_RelatorioBTMouseClicked

    private void RelatorioBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatorioBTMouseEntered
        //troca a cor do botao quanddo o mouse entra na area dele
        RelatorioBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_RelatorioBTMouseEntered

    private void RelatorioBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatorioBTMouseExited
        //troca a cor do botao quanddo o mouse sai da area dele
        RelatorioBT.setBackground(new Color(89, 149, 124));
    }//GEN-LAST:event_RelatorioBTMouseExited

    private void RelatorioBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatorioBTMousePressed
        // troca a cor do botao quando ele for precionado
        RelatorioBT.setBackground(new Color(74, 129, 107));
    }//GEN-LAST:event_RelatorioBTMousePressed

    private void RelatorioBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatorioBTMouseReleased
        // troca a cor do botao quando ele for solto:
        RelatorioBT.setBackground(new Color(107, 179, 144));
    }//GEN-LAST:event_RelatorioBTMouseReleased

    private void CancelarAcademiaBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarAcademiaBTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarAcademiaBTMouseClicked

    private void CancelarAcademiaBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarAcademiaBTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarAcademiaBTMouseEntered

    private void CancelarAcademiaBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarAcademiaBTMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarAcademiaBTMouseExited

    private void CancelarAcademiaBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarAcademiaBTMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarAcademiaBTMousePressed

    private void CancelarAcademiaBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarAcademiaBTMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarAcademiaBTMouseReleased

    private void SalvarAcademiaBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBTMouseClicked
        CadastroAcad acad = new CadastroAcad();
        acad.insertAcademia(RazaoSocialText.getText(),NomeFantasiaText.getText(),NomeResponsavelText.getText(),Integer.parseInt(CnpjText.getText()),Integer.parseInt(TelefoneText.getText()),Integer.parseInt(CepText.getText()));
    }//GEN-LAST:event_SalvarAcademiaBTMouseClicked

    private void SalvarAcademiaBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBTMouseEntered

    private void SalvarAcademiaBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBTMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBTMouseExited

    private void SalvarAcademiaBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBTMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBTMousePressed

    private void SalvarAcademiaBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBTMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBTMouseReleased

    private void CancelarEquipamentoBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarEquipamentoBTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarEquipamentoBTMouseClicked

    private void CancelarEquipamentoBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarEquipamentoBTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarEquipamentoBTMouseEntered

    private void CancelarEquipamentoBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarEquipamentoBTMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarEquipamentoBTMouseExited

    private void CancelarEquipamentoBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarEquipamentoBTMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarEquipamentoBTMousePressed

    private void CancelarEquipamentoBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarEquipamentoBTMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarEquipamentoBTMouseReleased

    private void SalvarAcademiaBT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBT1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBT1MouseClicked

    private void SalvarAcademiaBT1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBT1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBT1MouseEntered

    private void SalvarAcademiaBT1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBT1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBT1MouseExited

    private void SalvarAcademiaBT1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBT1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBT1MousePressed

    private void SalvarAcademiaBT1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarAcademiaBT1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarAcademiaBT1MouseReleased

    private void SelecionarAcademiaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SelecionarAcademiaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecionarAcademiaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CNPJ;
    private javax.swing.JLabel CNPJ1;
    private javax.swing.JLabel CadAcademiaBT;
    private javax.swing.JPanel CadAcademiaPane4;
    private javax.swing.JPanel CadAcademiaPane5;
    private javax.swing.JLabel CadEquipamentoBT;
    private javax.swing.JPanel CadastroAcademiaPane;
    private javax.swing.JPanel CadastroEquipamentoPane;
    private javax.swing.JLabel CadastroEquipamentos;
    private javax.swing.JLabel CadastroEquipamentos1;
    private javax.swing.JLabel CancelarAcademiaBT;
    private javax.swing.JLabel CancelarEquipamentoBT;
    private javax.swing.JLabel Cep;
    private javax.swing.JTextField CepText;
    private javax.swing.JLabel CnpjEquipamento;
    private javax.swing.JTextField CnpjEquipamentoText;
    private javax.swing.JFormattedTextField CnpjPesquisa;
    private javax.swing.JTextField CnpjText;
    private javax.swing.JButton FecharBt;
    private javax.swing.JTabbedPane Janelas;
    private javax.swing.JLabel NomeEquipamento;
    private javax.swing.JTextField NomeEquipamentoText1;
    private javax.swing.JLabel NomeFantasia;
    private javax.swing.JTextField NomeFantasiaText;
    private javax.swing.JLabel NomeResponsavel;
    private javax.swing.JTextField NomeResponsavelText;
    private javax.swing.JLabel NumSerie;
    private javax.swing.JLabel NumSerie1;
    private javax.swing.JTextField NumSerieText;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel RazaoSocial;
    private javax.swing.JTextField RazaoSocialSelecionar;
    private javax.swing.JTextField RazaoSocialText;
    private javax.swing.JLabel RelatorioBT;
    private javax.swing.JLabel SalvarAcademiaBT;
    private javax.swing.JLabel SalvarAcademiaBT1;
    private javax.swing.JButton SalvarBT1;
    private javax.swing.JTable SelecionarAcademia;
    private javax.swing.JLabel SelecionarBT;
    private javax.swing.JPanel SelecionarPane;
    private javax.swing.JScrollPane TabelaScrollPane;
    private javax.swing.JPanel TelaPrincipalPane;
    private javax.swing.JLabel Telefone;
    private javax.swing.JTextField TelefoneText;
    private javax.swing.JLabel cadastroacademia;
    // End of variables declaration//GEN-END:variables
}
